spring.application.name=petshop-backend
spring.datasource.url=jdbc:mysql://localhost:3306/projeto_tcc
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true